[sharing-fraction]
header = "The *Sharing Fraction* shows the resource-sharing effort of cells towards each of their neighboring cells."
items = [
    "[Black](#000000) grid tiles are *dead cells*.",
    "[White](#FFFFFF) indicates *zero resource* was received.",
    "[Blue](#0000FF) indicates a *small amount* of resource-sharing effort.",
    "[Green](#00FF00) indicates an *intermediate amount* of resource-sharing.",
    "[Yellow](#FFFF00) indicates a *large amount* of sharing effort.",
    "[White](#FFFFFF) borders divide *low-level groups* that are part of the same high-level group. ",
    "[Black](#000000) borders divide *high-level groups*."
]
[sharing-fraction-interconnect]
header = "The *Sharing Fraction* shows the resource-sharing effort of cells towards their outgoing interconnects."
items = [
    "[Black](#000000) grid tiles are *dead cells*.",
    "[White](#FFFFFF) indicates *zero resource* was received.",
    "[Blue](#0000FF) indicates a *small amount* of resource-sharing effort.",
    "[Green](#00FF00) indicates an *intermediate amount* of resource-sharing.",
    "[Yellow](#FFFF00) indicates a *large amount* of sharing effort.",
    "[White](#FFFFFF) borders divide *low-level groups* that are part of the same high-level group. ",
    "[Black](#000000) borders divide *high-level groups*."
]
[channel]
header = "The *Channel Viewer* shows the arrangement of hereditarily-defined resource-collecing cell groups."
items = [
    "*Color saturation* (e.g., [light green](#BFFFBF) vs. [intense green](#00FF00) ) differentiates *low-level groups*.",
    "*Color hue* (e.g., [light blue](#BFBFFF) / [intense blue](#0000FF) vs. [light purple](#FFBFFF) / [intense purple](#FF00FF) ) differentiates *high-level groups*, which are groups of low-level groups. ",
    "[White](#FFFFFF) borders divide *low-level groups* that are part of the same high-level group. ",
    "[Black](#000000) borders divide *high-level groups*."
]
[resource-stockpile]
header = "The *Stockpile Viewer* depicts the resource that each cell-like organism has accumulated."
items = [
    "[Black](#000000) grid tiles are *dead cells*.",
    "[Red](#FF0000) indicates a *resource defecit* (which, if it becomes too extreme, will result in that cell's death).",
    "[White](#FFFFFF) indicates *zero resource*.",
    "[Blue](#0000FF) indicates *positive resource*, but below the threshold required for reproduction.",
    "[Green](#00FF00) indicates *enough resource to reproduce*.",
    "[Yellow](#FFFF00) indicates an *excess of resource*, more than enough to reproduce.",
    "[White](#FFFFFF) borders divide *low-level groups* that are part of the same high-level group. ",
    "[Black](#000000) borders divide *high-level groups*."
]
[resource-sharing]
header = "The *Contribution Viewer* depicts the amount of resource has received from neighbors during the previous update."
items = [
    "[Black](#000000) grid tiles are *dead cells*.",
    "[White](#FFFFFF) indicates *zero resource* was received.",
    "[Blue](#0000FF) indicates a *small amount* of resource was received.",
    "[Green](#00FF00) indicates an *intermediate amount* of resource was received.",
    "[Yellow](#FFFF00) indicates a *large amount* of resource was received.",
    "[White](#FFFFFF) borders divide *low-level groups* that are part of the same high-level group. ",
    "[Black](#000000) borders divide *high-level groups*."
]
[apoptosis]
header = "The *Apoptosis Viewer* shows cells that have registered themselves for imminent cellular suicidie."
items = [
    "[Black](#000000) grid tiles are *dead cells*.",
    "[White](#FFFFFF) grid tiles are *live cells*.",
    "[Blue](#0000FF) cells are registered for *partial apoptosis*, where a underlying cell is destroyed but its channel structure is preserved.",
    "[Red](#FF0000) cells are registered for *complete apoptosis*, where a cell and its channel structure are totally destroyed.",
    "[White](#FFFFFF) borders divide *low-level groups* that are part of the same high-level group. ",
    "[Black](#000000) borders divide *high-level groups*."
]
[taxa]
header = "The *Taxa Viewer* depicts the distribution of groups of genetically-identical cells."
items = [
    "[Black](#000000) grid tiles are *dead cells*.",
    "[White](#FFFFFF) grid tiles are *live cells*.",
    "[White](#FFFFFF) lines divide cells with *identical genotypes*.",
    "[Red](#FF0000) lines divide cells with *different genotypes*."
]
[resource-wave]
header = ["The *Resource Wave Viewer* depicts the cells' cooperative resource-collection task.",
          "Activation propagates outward in same-channel groups from an environmentally-triggered seed."]
items = [
    "[Green](#00FF00) cells are activated within the beneficial radius of the seed and are *gaining resource*.",
    "[Red](#FF0000) cells are activated outside the beneficial radius of the seed and are *losing resource*.",
    "[White](#FFFFFF) cells are in the *ready state*, meaning they can be activated by adjacent cooperating cells.",
    "[Blue](#0000FF) cells are in a *quiescent state*, meaning they cannot be activated by adjacent cooperating cells.",
    "[Black](#000000) grid tiles are *dead cells*.",
    "[White](#FFFFFF) borders divide *low-level groups* that are part of the same high-level group. ",
    "[Black](#000000) borders divide *high-level groups*."

]

[channel-generation]
header = "The *Channel Generation Viewer* depicts generation counters that enforce a birth-death lifecycle."
items = [
    "[White](#FFFFFF) cells are *young* members of a same-channel group. They are capable of collecting resource and producing offspring that are group members.",
    "[Blue](#0000FF) cells are *older* members of a same-channel group, which still retain all the capabilities of younger cells.",
    "[Red](#FF0000) cells are *oldest* members of a same-channel group. As coloring progress from light to dark red, cells lose their ability to create same-channel offspring and then to collect resource.",
    "[Black](#000000) grid tiles are *dead cells*.",
    "[White](#FFFFFF) borders divide *low-level groups* that are part of the same high-level group. ",
    "[Black](#000000) borders divide *high-level groups*."
]
[expiration]
header = "The *Expiration Viewer* depicts end-of-the-road channel generation state in greater detail."
items = [
    "[White](#FFFFFF) cells are *young* and retain all reproductive and resource-collection capabilities.",
    "[Blue](#0000FF) cells are *older* and have lost same-channel reproductive capability.",
    "[Red](#FF0000) cells are *oldest* and have additionally lost resource-collection capability.",
    "[Black](#000000) grid tiles are *dead cells*.",
    "[White](#FFFFFF) borders divide *low-level groups* that are part of the same high-level group. ",
    "[Black](#000000) borders divide *high-level groups*."
]

[reproductive-pause]
header = "The *Reproductive Pause Viewer* depicts reproductive cooperation."
items = [
    "[White](#FFFFFF) cells have registered *zero* reproductive forbearance.",
    "[Green](#00FF00) cells have temporarily registred to pause reproduction in *one direction*.",
    "[Blue](#0000FF) cells have temporariliy registered to pause reproduction in *two directions*.",
    "[Purple](#FF00FF) cells have temporariliy registered to pause reproduction in *three directions*.",
    "[Red](#FF0000) cells have temporarily registered to pause reproduction in all *four directions*.",
    "[Black](#000000) grid tiles are *dead cells*.",
    "[White](#FFFFFF) borders divide *low-level groups* that are part of the same high-level group. ",
    "[Black](#000000) borders divide *high-level groups*."
]
